### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by Jyrno42** [CubeBackup/docker#2]
Hey. Thanks for this tool. Any chance you can also provide us with an arm compatible image? Would like to run this inside a Raspberry Pi based kubernetes cluster.

Tried building it myself but received the following error during build:

```
Step 2/4 : RUN curl -s https://v4beta.cubebackup.com/install.sh | bash
 ---> Running in 23ec92884cd6
ERROR: This package can only be installed on Linux x86_64 system
The command '/bin/sh -c curl -s https://v4beta.cubebackup.com/install.sh | bash' returned a non-zero code: 1
```

**Comment by jerrywjh** [comment]
Hi Jurno,

Thanks for trying our product.

CubeBackup is only available on x86 system.   Currently, We have no plan to
provide an Arm compatible version yet. Make it workable on an Arm system
can take considerable time and effort,  but we do not have enough time now.

Best regards,

**Comment by Jyrno42** [comment]
Ok thanks for letting me know. Will add an intel based node to my cluster then.

**Comment by janhoy** [comment]
Hi @jerrywjh. Facing the same issue. Considering setting up CubeBackup for a no-profit org with 15 users.

AMD systems are more expensive to run than ARM, so would appreciate if you did an attempt to build ARM binaries and a dual architecture docker build, which is very common for almost all tools these days. Another benefit of providing this is that all M based Macs would then run the docker image without emulation during evaluation and testing.
